apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-deployment
  namespace: openshift-monitoring
spec:
  replicas: 3
  selector:
    matchLabels:
      app: telegraf
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
        - image: nexus.openshift.training:8090/docker/telegraf:1.31.2
          name: telegraf
          volumeMounts:
            - mountPath: /etc/telegraf/telegraf.conf
              name: telegraf-config
              subPath: telegraf.conf
              readOnly: true
            - name: telegraf-ca-cert
              readOnly: true
              mountPath: "/etc/telegraf/ca/service-ca.crt"
              subPath: service-ca.crt
            - name: service-secret-tls
              readOnly: true
              mountPath: "/etc/telegraf/tls/"
          envFrom:
            - secretRef:
                name: telegraf-secrets
          resources:
            limits:
              cpu: 500m
              memory: 2G
      volumes:
        - name: telegraf-config
          configMap:
            name: telegraf-config
        - name: telegraf-ca-cert
          configMap:
            name: telegraf-ca-cert
        - name: service-secret-tls
          secret:
            secretName: telegraf-service-tls 